/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/admin/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 管理员查看系统统计
         * @description 获取用户总数、会员等级分布和账号状态等运营数据
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"] & {
                            data?: components["schemas"]["admin.StatsResponse"];
                        };
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 管理员获取用户列表
         * @description 分页获取所有用户信息，支持按 email、username、role、status 过滤
         */
        get: {
            parameters: {
                query?: {
                    /** @description 页码 */
                    page?: number;
                    /** @description 每页数量 */
                    page_size?: number;
                    /** @description email 模糊搜索 */
                    email?: string;
                    /** @description username 模糊搜索 */
                    username?: string;
                    /** @description 角色过滤 (user/premium) */
                    role?: string;
                    /** @description 管理员权限过滤 */
                    is_admin?: boolean;
                    /** @description 状态过滤 (active/banned) */
                    status?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"] & {
                            data?: components["schemas"]["admin.UserListResponse"];
                        };
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 管理员获取用户详情
         * @description 获取指定用户的完整信息，用于前端编辑表单回填
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 用户 ID */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"] & {
                            data?: components["schemas"]["admin.UserResponse"];
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"];
                    };
                };
            };
        };
        /**
         * 管理员修改用户信息
         * @description 修改指定用户的 email、username、role、is_admin、status
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 用户 ID */
                    id: number;
                };
                cookie?: never;
            };
            /** @description 用户信息 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["admin.UpdateUserRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"] & {
                            data?: components["schemas"]["admin.UserResponse"];
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{id}/disable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 管理员禁用用户
         * @description 禁用指定用户，清除其所有 refresh token
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 用户 ID */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"] & {
                            data?: {
                                [key: string]: string;
                            };
                        };
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{id}/enable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 管理员启用用户
         * @description 解除对指定用户的禁用状态
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 用户 ID */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"] & {
                            data?: {
                                [key: string]: string;
                            };
                        };
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{id}/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * 管理员重置用户密码
         * @description 管理员为指定用户重置密码，重置后用户需重新登录
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 用户 ID */
                    id: number;
                };
                cookie?: never;
            };
            /** @description 新密码 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["admin.ResetPasswordRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"] & {
                            data?: {
                                [key: string]: string;
                            };
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{id}/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * 管理员修改用户角色
         * @description 修改指定用户的角色
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 用户 ID */
                    id: number;
                };
                cookie?: never;
            };
            /** @description 角色信息 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["admin.UpdateRoleRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"] & {
                            data?: {
                                [key: string]: string;
                            };
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 用户登录
         * @description 使用邮箱和密码登录，获取 Access Token 和 Refresh Token
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 登录信息 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["user.LoginRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"] & {
                            data?: components["schemas"]["user.TokenResponse"];
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 刷新 Access Token
         * @description 用 Refresh Token 换取新的双 Token
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Refresh Token */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["user.RefreshRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"] & {
                            data?: components["schemas"]["user.TokenResponse"];
                        };
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 用户注册
         * @description 使用邮箱和密码注册新账户
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 注册信息 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["user.RegisterRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"] & {
                            data?: components["schemas"]["user.Response"];
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取当前用户信息
         * @description 返回当前登录用户的个人信息
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"] & {
                            data?: components["schemas"]["user.Response"];
                        };
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * 用户修改自己的密码
         * @description 当前登录用户通过旧密码校验后修改自己的密码
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 密码信息 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["user.ChangePasswordRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"] & {
                            data?: {
                                [key: string]: string;
                            };
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/phone/send-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 发送手机号验证码
         * @description 当前登录用户向指定手机号发送验证码，用于绑定手机号
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 手机号 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["user.SendPhoneCodeRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"] & {
                            data?: {
                                [key: string]: string;
                            };
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/phone/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 校验手机号验证码
         * @description 当前登录用户校验验证码并完成手机号绑定
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 手机号与验证码 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["user.VerifyPhoneRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"] & {
                            data?: {
                                [key: string]: string;
                            };
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/membership": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取当前会员状态
         * @description 返回当前用户的 premium 会员状态和有效期
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"] & {
                            data?: components["schemas"]["membership.CurrentMembershipResponse"];
                        };
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/membership/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取会员套餐列表
         * @description 返回当前可购买的 premium 月卡、季卡、年卡套餐
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"] & {
                            data?: components["schemas"]["membership.PlanResponse"][];
                        };
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payment/callbacks/mock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** mock 支付回调 */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @description 非开发环境下必填的内部 mock 回调密钥 */
                    "X-Mock-Callback-Secret"?: string;
                };
                path?: never;
                cookie?: never;
            };
            /** @description mock 回调 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["payment.MockCallbackRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"] & {
                            data?: components["schemas"]["payment.OrderResponse"];
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payment/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查询我的支付订单 */
        get: {
            parameters: {
                query?: {
                    /** @description 页码 */
                    page?: number;
                    /** @description 每页数量 */
                    page_size?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"] & {
                            data?: components["schemas"]["payment.OrderListResponse"];
                        };
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"];
                    };
                };
            };
        };
        put?: never;
        /** 创建会员支付订单 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 订单信息 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["payment.CreateOrderRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"] & {
                            data?: components["schemas"]["payment.OrderResponse"];
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payment/orders/{order_no}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查询我的支付订单详情 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 订单号 */
                    order_no: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"] & {
                            data?: components["schemas"]["payment.OrderResponse"];
                        };
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payment/orders/{order_no}/detect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 主动检测订单支付状态 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 订单号 */
                    order_no: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"] & {
                            data?: components["schemas"]["payment.OrderResponse"];
                        };
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payment/orders/{order_no}/pay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** mock 支付会员订单 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 订单号 */
                    order_no: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"] & {
                            data?: components["schemas"]["payment.OrderResponse"];
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 健康检查
         * @description 检查服务及数据库连接状态
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"] & {
                            data?: {
                                [key: string]: string;
                            };
                        };
                    };
                };
                /** @description Service Unavailable */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "admin.ResetPasswordRequest": {
            /** @example newpass123 */
            new_password: string;
        };
        "admin.StatsResponse": {
            /** @example 950 */
            active_users?: number;
            /** @example 50 */
            banned_users?: number;
            /** @example 1000 */
            total_users?: number;
            users_by_role?: {
                [key: string]: number;
            };
        };
        "admin.UpdateRoleRequest": {
            /**
             * @example premium
             * @enum {string}
             */
            role: "user" | "premium";
        };
        "admin.UpdateUserRequest": {
            /** @example user@example.com */
            email?: string;
            /** @example false */
            is_admin?: boolean;
            /**
             * @example premium
             * @enum {string}
             */
            role?: "user" | "premium";
            /**
             * @example active
             * @enum {string}
             */
            status?: "active" | "banned";
            /** @example johndoe */
            username?: string;
        };
        "admin.UserListItem": {
            /** @example 2024-01-01T00:00:00Z */
            created_at?: string;
            /** @example user@example.com */
            email?: string;
            /** @example 1 */
            id?: number;
            /** @example false */
            is_admin?: boolean;
            /** @example 13800138000 */
            phone?: string;
            /** @example true */
            phone_verified?: boolean;
            /** @example user */
            role?: string;
            /** @example active */
            status?: string;
            /** @example johndoe */
            username?: string;
        };
        "admin.UserListResponse": {
            /** @example 1 */
            page?: number;
            /** @example 20 */
            page_size?: number;
            /** @example 100 */
            total?: number;
            users?: components["schemas"]["admin.UserListItem"][];
        };
        "admin.UserResponse": {
            /** @example 2024-01-01T00:00:00Z */
            created_at?: string;
            /** @example user@example.com */
            email?: string;
            /** @example 1 */
            id?: number;
            /** @example false */
            is_admin?: boolean;
            /** @example 13800138000 */
            phone?: string;
            /** @example true */
            phone_verified?: boolean;
            /** @example user */
            role?: string;
            /** @example active */
            status?: string;
            /** @example 2024-01-01T00:00:00Z */
            updated_at?: string;
            /** @example johndoe */
            username?: string;
        };
        "membership.CurrentMembershipResponse": {
            /** @example true */
            active?: boolean;
            /** @example 2026-05-23T10:00:00Z */
            ends_at?: string;
            /** @example premium */
            membership_level?: string;
            /** @example 2026-04-23T10:00:00Z */
            started_at?: string;
            /** @example active */
            status?: string;
        };
        "membership.PlanResponse": {
            /** @example CNY */
            currency?: string;
            /** @example 30 */
            duration_days?: number;
            /** @example 1 */
            id?: number;
            /** @example premium */
            membership_level?: string;
            /** @example monthly */
            plan_code?: string;
            /** @example 月度会员 */
            plan_name?: string;
            /** @example 990 */
            price_amount?: number;
            /** @example active */
            status?: string;
        };
        "payment.CreateOrderRequest": {
            /** @example checkout-123 */
            idempotency_key?: string;
            /**
             * @example monthly
             * @enum {string}
             */
            plan_code: "monthly" | "quarterly" | "yearly";
        };
        "payment.MockCallbackRequest": {
            /** @example mock-callback-1 */
            callback_id: string;
            /** @example MOCK202604231200000001 */
            channel_trade_no: string;
            /** @example MO202604231200000001 */
            order_no: string;
            /** @example true */
            success?: boolean;
        };
        "payment.OrderListResponse": {
            items?: components["schemas"]["payment.OrderResponse"][];
            /** @example 1 */
            page?: number;
            /** @example 20 */
            page_size?: number;
            /** @example 1 */
            total?: number;
        };
        "payment.OrderResponse": {
            /** @example 990 */
            amount?: number;
            /** @example 2026-04-23T10:15:00Z */
            closed_at?: string;
            /** @example 2026-04-23T10:00:00Z */
            created_at?: string;
            /** @example CNY */
            currency?: string;
            /** @example pending */
            entitlement_status?: string;
            /** @example 2026-04-23T10:15:00Z */
            expires_at?: string;
            /** @example MO202604231200000001 */
            order_no?: string;
            /** @example awaiting_payment */
            order_status?: string;
            /** @example 2026-04-23T10:01:00Z */
            paid_at?: string;
            /** @example mock */
            payment_channel?: string;
            /** @example unpaid */
            payment_status?: string;
            /** @example monthly */
            plan_code?: string;
            /** @example 月度会员 */
            subject?: string;
            /** @example 1 */
            user_id?: number;
        };
        "user.ChangePasswordRequest": {
            /** @example oldpass123 */
            current_password: string;
            /** @example newpass123 */
            new_password: string;
        };
        "user.LoginRequest": {
            /** @example user@example.com */
            email: string;
            /** @example pass1234 */
            password: string;
        };
        "user.RefreshRequest": {
            /** @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9... */
            refresh_token: string;
        };
        "user.RegisterRequest": {
            /** @example user@example.com */
            email: string;
            /** @example pass1234 */
            password: string;
        };
        "user.Response": {
            /** @example 2024-01-01T00:00:00Z */
            created_at?: string;
            /** @example user@example.com */
            email?: string;
            /** @example 1 */
            id?: number;
            /** @example false */
            is_admin?: boolean;
            /** @example 13800138000 */
            phone?: string;
            /** @example true */
            phone_verified?: boolean;
            /** @example user */
            role?: string;
            /** @example active */
            status?: string;
            /** @example johndoe */
            username?: string;
        };
        "user.SendPhoneCodeRequest": {
            /** @example 13800138000 */
            phone: string;
        };
        "user.TokenResponse": {
            /** @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9... */
            access_token?: string;
            /** @example 900 */
            expires_in?: number;
            /** @example abc123... */
            refresh_token?: string;
        };
        "user.VerifyPhoneRequest": {
            /** @example 123456 */
            code: string;
            /** @example 13800138000 */
            phone: string;
        };
        "web.Response": {
            code?: number;
            data?: unknown;
            message?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
