/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/admin/bindings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 管理员查看所有绑定关系
         * @description 分页获取所有家长-学生绑定关系
         */
        get: {
            parameters: {
                query?: {
                    /** @description 页码 */
                    page?: number;
                    /** @description 每页数量 */
                    page_size?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"] & {
                            data?: components["schemas"]["admin.BindingListResponse"];
                        };
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/bindings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * 管理员解除绑定
         * @description 仅管理员可调用，解除家长-学生绑定关系
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Binding ID */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"] & {
                            data?: {
                                [key: string]: string;
                            };
                        };
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 管理员查看系统统计
         * @description 获取用户总数、绑定总数等运营数据
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"] & {
                            data?: components["schemas"]["admin.StatsResponse"];
                        };
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 管理员获取用户列表
         * @description 分页获取所有用户信息，支持按 email、username、role、status 过滤
         */
        get: {
            parameters: {
                query?: {
                    /** @description 页码 */
                    page?: number;
                    /** @description 每页数量 */
                    page_size?: number;
                    /** @description email 模糊搜索 */
                    email?: string;
                    /** @description username 模糊搜索 */
                    username?: string;
                    /** @description 角色过滤 (user/premium/admin) */
                    role?: string;
                    /** @description 状态过滤 (active/banned) */
                    status?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"] & {
                            data?: components["schemas"]["admin.UserListResponse"];
                        };
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{id}/disable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 管理员禁用用户
         * @description 禁用指定用户，清除其所有 refresh token
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 用户 ID */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"] & {
                            data?: {
                                [key: string]: string;
                            };
                        };
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{id}/enable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 管理员启用用户
         * @description 解除对指定用户的禁用状态
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 用户 ID */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"] & {
                            data?: {
                                [key: string]: string;
                            };
                        };
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{id}/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * 管理员修改用户角色
         * @description 修改指定用户的角色
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 用户 ID */
                    id: number;
                };
                cookie?: never;
            };
            /** @description 角色信息 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["admin.UpdateRoleRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"] & {
                            data?: {
                                [key: string]: string;
                            };
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analysis/enrollment-plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取招生计划数据
         * @description 获取模拟的招生计划数据，支持分页和筛选
         */
        get: {
            parameters: {
                query?: {
                    /** @description 学校名称 */
                    school_name?: string;
                    /** @description 专业名称 */
                    major_name?: string;
                    /** @description 省份 */
                    province?: string;
                    /** @description 年份 */
                    year?: number;
                    /** @description 批次 */
                    batch?: string;
                    /** @description 页码，默认1 */
                    page?: number;
                    /** @description 每页数量，默认10 */
                    per_page?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"] & {
                            data?: components["schemas"]["analysis.EnrollmentPlanResponse"];
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 用户登录
         * @description 使用邮箱和密码登录，获取 Access Token 和 Refresh Token
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 登录信息 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["user.LoginRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"] & {
                            data?: components["schemas"]["user.TokenResponse"];
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 刷新 Access Token
         * @description 用 Refresh Token 换取新的双 Token
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Refresh Token */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["user.RefreshRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"] & {
                            data?: components["schemas"]["user.TokenResponse"];
                        };
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 用户注册
         * @description 使用邮箱和密码注册新账户
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 注册信息 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["user.RegisterRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"] & {
                            data?: components["schemas"]["user.Response"];
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bindings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 查询我的绑定关系
         * @description 家长返回绑定的学生列表，学生返回绑定的家长信息
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"] & {
                            data?: components["schemas"]["user.BindingListResponse"];
                        };
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"];
                    };
                };
            };
        };
        put?: never;
        /**
         * 发起家长-学生绑定
         * @description 家长通过学生邮箱发起绑定，即时生效
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 绑定信息 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["user.CreateBindingRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"] & {
                            data?: components["schemas"]["user.BindingResponse"];
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取当前用户信息
         * @description 返回当前登录用户的个人信息
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"] & {
                            data?: components["schemas"]["user.Response"];
                        };
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 健康检查
         * @description 检查服务及数据库连接状态
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"] & {
                            data?: {
                                [key: string]: string;
                            };
                        };
                    };
                };
                /** @description Service Unavailable */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["web.Response"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "admin.BindingListItem": {
            /** @example 2024-01-01T00:00:00Z */
            created_at?: string;
            /** @example 1 */
            id?: number;
            parent?: components["schemas"]["admin.SafeUserInfo"];
            student?: components["schemas"]["admin.SafeUserInfo"];
        };
        "admin.BindingListResponse": {
            bindings?: components["schemas"]["admin.BindingListItem"][];
            /** @example 1 */
            page?: number;
            /** @example 20 */
            page_size?: number;
            /** @example 100 */
            total?: number;
        };
        "admin.SafeUserInfo": {
            /** @example user@example.com */
            email?: string;
            /** @example 1 */
            id?: number;
        };
        "admin.StatsResponse": {
            /** @example 950 */
            active_users?: number;
            /** @example 50 */
            banned_users?: number;
            /** @example 500 */
            total_bindings?: number;
            /** @example 1000 */
            total_users?: number;
            users_by_role?: {
                [key: string]: number;
            };
        };
        "admin.UpdateRoleRequest": {
            /**
             * @example premium
             * @enum {string}
             */
            role: "user" | "premium" | "admin";
        };
        "admin.UserListItem": {
            /** @example 2024-01-01T00:00:00Z */
            created_at?: string;
            /** @example user@example.com */
            email?: string;
            /** @example 1 */
            id?: number;
            /** @example user */
            role?: string;
            /** @example active */
            status?: string;
            /** @example student */
            user_type?: string;
            /** @example johndoe */
            username?: string;
        };
        "admin.UserListResponse": {
            /** @example 1 */
            page?: number;
            /** @example 20 */
            page_size?: number;
            /** @example 100 */
            total?: number;
            users?: components["schemas"]["admin.UserListItem"][];
        };
        "analysis.EnrollmentPlan": {
            /** @description 实际招生人数 */
            actual_count?: number;
            /** @description 平均分数线 */
            average_score?: number;
            /** @description 批次（一本、二本等） */
            batch?: string;
            id?: number;
            /** @description 专业代码 */
            major_code?: string;
            /** @description 专业名称 */
            major_name?: string;
            /** @description 最高分数线 */
            max_score?: number;
            /** @description 最低分数线 */
            min_score?: number;
            /** @description 计划招生人数 */
            plan_count?: number;
            /** @description 省份 */
            province?: string;
            /** @description 学校代码 */
            school_code?: string;
            /** @description 学校名称 */
            school_name?: string;
            /** @description 科目要求 */
            subject_require?: string;
            /** @description 年份 */
            year?: number;
        };
        "analysis.EnrollmentPlanResponse": {
            /** @description 当前页码 */
            page?: number;
            /** @description 每页数量 */
            per_page?: number;
            /** @description 招生计划列表 */
            plans?: components["schemas"]["analysis.EnrollmentPlan"][];
            /** @description 总数据量 */
            total?: number;
        };
        "user.BindingListResponse": {
            bindings?: components["schemas"]["user.BindingWithUserDetail"][];
            /** @example parent */
            user_type?: string;
        };
        "user.BindingResponse": {
            /** @example 2026-04-20T10:00:00Z */
            created_at?: string;
            /** @example 1 */
            id?: number;
            /** @example 2 */
            parent_id?: number;
            /** @example 5 */
            student_id?: number;
        };
        "user.BindingWithUserDetail": {
            created_at?: string;
            id?: number;
            user?: components["schemas"]["user.SafeUser"];
        };
        "user.CreateBindingRequest": {
            /** @example xiaoming@example.com */
            student_email: string;
        };
        "user.LoginRequest": {
            /** @example user@example.com */
            email: string;
            /** @example pass1234 */
            password: string;
        };
        "user.RefreshRequest": {
            /** @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9... */
            refresh_token: string;
        };
        "user.RegisterRequest": {
            /** @example user@example.com */
            email: string;
            /** @example pass1234 */
            password: string;
            /**
             * @example parent
             * @enum {string}
             */
            user_type: "parent" | "student";
        };
        "user.Response": {
            /** @example 2024-01-01T00:00:00Z */
            created_at?: string;
            /** @example user@example.com */
            email?: string;
            /** @example 1 */
            id?: number;
            /** @example user */
            role?: string;
            /** @example active */
            status?: string;
            /** @example parent */
            user_type?: string;
            /** @example johndoe */
            username?: string;
        };
        "user.SafeUser": {
            email?: string;
            id?: number;
        };
        "user.TokenResponse": {
            /** @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9... */
            access_token?: string;
            /** @example 900 */
            expires_in?: number;
            /** @example abc123... */
            refresh_token?: string;
        };
        "web.Response": {
            code?: number;
            data?: unknown;
            message?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
